### PR TITLE
Update to 0.8.1 release

### PR DESCRIPTION
**Pull request by chapmanb**
Closes https://github.com/conda-forge/bazel-feedstock/pull/1 ( edit by @jakirkham )

- Removes ld gold patch which has been fixed upstream
- Fixes problems with missing license file by pointing to right file

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by chapmanb** [comment]
@jakirkham Thanks much for the help getting this re-rendered. It looks like all the tests are passing cleanly.

**Comment by jakirkham** [comment]
Could you please review @jjhelmus?

**Comment by chapmanb** [comment]
I wanted to bump to see if we could get this merged. Hopefully my changes are pretty easy to double check. I bumped the bazel version and then removed a patch which is no longer needed, here is the closed upstream report it fiixed in that older version: https://github.com/bazelbuild/bazel/issues/2502. Let me know if I can help with anything else.

**Comment by ocefpaf** [comment]
LGTM. @jjhelmus is probably busy with the day job so merging this. Thanks @chapmanb!

**Comment by chapmanb** [comment]
Brilliant, thanks so much for merging.

**Pull request merged**
