### PR TITLE
updated for the bazel-0.5.4 release

### PR DESCRIPTION
**Pull request by abhi18av**
Updating the package version

### CODE REVIEW

**Comment by abhi18av** [comment]
The `Circle-CI` error seems to be more intuitive. I'm pasting it here so 'cos I need a bit of help debugging this 

```python3
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 133, in _copy_with_shell_fallback
    stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cp -a /feedstock_root/build_artefacts/bazel_1506240730791/work/LICENSE.txt /feedstock_root/build_artefacts/bazel_1506240730791/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/info/LICENSE.txt' returned non-zero exit status 1.

```

Correct me if I'm wrong, the `License.txt` needs to be there as per new conda policy?

**Comment by jakirkham** [comment]
Yeah it needs to be there. Would try downloading the tarball locally and seeing if they renamed the license file or something.

**Comment by jakirkham** [comment]
Have skipped ahead to `0.8.1` in PR ( https://github.com/conda-forge/bazel-feedstock/pull/2 ). Not sure if that works for you @abhi18av. If not, we can take the old release on a different branch if you are still interested. Would still welcome you as a maintainer either way.

**Comment by abhi18av** [comment]
Yup @jakirkham count me in for being a maintainer 👍

**Comment by jakirkham** [comment]
Of course. Feel free to submit a fresh PR just adding your name to the list. Also please add `[ci skip]` in the commit message as we don't need to run the tests on it. Thanks.

**Pull request closed without merging**
