### PR TITLE
update to 5.4.1

### PR DESCRIPTION
**Pull request by mattip**
Package bazel 5.4.1

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is the version used in building ray-2.6

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
Hmm. CI is not running on this branch?

**Comment by mattip** [comment]
singlejar and ijar versions used in the recipe are tied to this version, so they will also need a 5.4.1 relelase

**Comment by mattip** [comment]
Close/reopen now that ijar and singlejar 5.4.1 exist.

**Comment by h-vetinari** [comment]
> Close/reopen now that ijar and singlejar 5.4.1 exist.

I was already doing the restarts manually. Close/reopen now redoes the jobs that already passed before (like windows), and delays the process. Not the end of the world, but FYI

**Comment by mattip** [comment]
Thanks, sorry for delaying things.

**Pull request merged**
