### PR TITLE
4.2.1 abseil pin correctly

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@xhochy is this one ok too? Sorry, i didn't add the abseil pin in host in the previous one. I think this seems to be passing well.

**Comment by xhochy** [comment]
Did you forget to add the migration file to the commit? Otherwise looks fine.

**Comment by hmaarrfk** [comment]
I merged earlier, before adding the line `abseil-cpp` to build. Ok. lets merge this.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Pull request merged**
