### PR TITLE
bazel v6.5.0

### PR DESCRIPTION
**Pull request by h-vetinari**
Based on #208

Cross-compilation jobs need to wait for builds from https://github.com/conda-forge/singlejar-feedstock/pull/69 & https://github.com/conda-forge/ijar-feedstock/pull/30 to hit the CDN.

### CODE REVIEW

**Comment by h-vetinari** [comment]
So the cross-compiled builds stumble over building the vendored blake3, which tries to compile some x64 assembly. Presumably we can just skip that (or build blake3 separately)?

Windows runs into:
```
scripts/bootstrap/compile.sh: line 447: /lib/jvm/bin/java: Argument list too long
```
which is going to be even more painful to work around much less fix.

**Comment by xhochy** [comment]
> which is going to be even more painful to work around much less fix.

One approach has always been to unset some environment variables as they are also passed in via the commandline. A lot of them are irrelevant for the build.

**Comment by mattip** [comment]
> So the cross-compiled builds stumble over building the vendored blake3, which tries to compile some x64 assembly

I am also hitting this in conda-forge/ray-packages-feedstock#158 when cross-compiling boost. I think more modern bazel uses `--platform` instead of `--cpu`, but I can't exactly figure out the proper incantation

**Comment by xhochy** [comment]
> > So the cross-compiled builds stumble over building the vendored blake3, which tries to compile some x64 assembly
> 
> I am also hitting this in [conda-forge/ray-packages-feedstock#158](https://github.com/conda-forge/ray-packages-feedstock/pull/158) when cross-compiling boost. I think more modern bazel uses `--platform` instead of `--cpu`, but I can't exactly figure out the proper incantation

This is the root of the issue. We need to migrate `bazel-toolchain` to be a proper argument to `--platform` and then we should also be able to build Bazel 7.

**Comment by ConorForgie** [comment]
Yep second that. Epic effort on this & jaxlib!

**Pull request merged**
