### PR TITLE
3.1.0

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks a lot @nehaljwani for tackling this so quickly! :)

While you branched off at 2.1.0, I assume you're reflecting much of the changes that have landed in master in this PR already? 

In any case, OSX seems to not be finding pthread, but I don't know where to add that for bazel.
```
src/main/cpp/blaze_util_darwin.cc:24:10: fatal error: 'pthread/spawn.h' file not found
#include <pthread/spawn.h>
         ^~~~~~~~~~~~~~~~~
```

Maybe adding [pthread-stubs](https://github.com/conda-forge/pthread-stubs-feedstock) might help?

**Comment by nehaljwani** [comment]
@h-vetinari It was a mishap with SDK config and missing patches. All good now!

**Comment by h-vetinari** [comment]
@nehaljwani 
This failed on the branch, I think because it didn't have all the admin-migration stuff regarding CFEP-13.

**Comment by h-vetinari** [comment]
Created a PR that should fix it: #56

**Pull request merged**
