### PR TITLE
Attempt windows build

### PR DESCRIPTION
**Pull request by adrianchia**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianchia** [comment]
@conda-forge-admin please rerender

**Comment by Anthchirp** [comment]
@conda-forge/bazel looks like this is ready to be merged

**Comment by aregm** [comment]
@jjhelmus @nehaljwani @jschueller @abhi18av - Can you guys merge this PR if everything is ok?

**Comment by vnlitvinov** [comment]
Should be closing #36 when merged.

**Comment by nehaljwani** [comment]
@conda-forge-admin please re-render!

**Pull request merged**
