### PR TITLE
[6.x] Rebuild for libgrpc 1.63 & libprotobuf 5.26.1

### PR DESCRIPTION
**Pull request by h-vetinari**
To unblock `protobuf`, which now needs bazel

### CODE REVIEW

**Comment by h-vetinari** [comment]
@xhochy, I'm getting stuck here with:
```
ERROR: /home/conda/feedstock_root/build_artifacts/bazel_1721195919371/work/src/main/java/com/google/devtools/build/lib/util/io/BUILD:21:13: Building src/main/java/com/google/devtools/build/lib/util/io/libio.jar (17 source files) failed: (Exit 1): java failed: error executing command (from target //src/main/java/com/google/devtools/build/lib/util/io:io) 
  (cd /tmp/bazel_G24DZlpl/out/execroot/io_bazel && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
    PATH=/home/conda/feedstock_root/build_artifacts/bazel_1721195919371/_build_env/bin:/home/conda/feedstock_root/build_artifacts/bazel_1721195919371/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin:/opt/conda/condabin:/home/conda/feedstock_root/build_artifacts/bazel_1721195919371/_build_env/bin:/home/conda/feedstock_root/build_artifacts/bazel_1721195919371/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/conda/bin \
  external/local_jdk/bin/java -Xmx512m -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar bazel-out/k8-opt-exec-EDC14992/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_VanillaJavaBuilder_deploy.jar @bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/util/io/libio.jar-0.params @bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/util/io/libio.jar-1.params)
# Configuration: abb7fdfaed9f1885ed99005ea85ccbd24a7cc37dc7f116d825144157c9572d1b
# Execution platform: //:default_host_platform
src/main/java/com/google/devtools/build/lib/util/io/MessageOutputStreamWrapper.java:50: error: method includingDefaultValueFields in class com.google.protobuf.util.JsonFormat.Printer cannot be applied to given types;
  required: java.util.Set<com.google.protobuf.Descriptors.FieldDescriptor>
  found: no arguments
  reason: actual and formal argument lists differ in length
```

Not sure if this is something related to the openjdk version (c.f. https://github.com/bazelbuild/bazel/issues/22789), or if it's due to protobuf 26 bumping the java major version from 3 to 4... Any idea?

FWIW, that call (without arguments) still [exists](https://github.com/bazelbuild/bazel/blob/4112c1c3f176d3ae21a4c26e110c16c36f1b3b55/src/main/java/com/google/devtools/build/lib/util/io/MessageOutputStreamWrapper.java#L53) in bazel main branch; not sure if bazel itself is incompatible with protobuf (java) 4.26+.

**Comment by xhochy** [comment]
This is breaking change in Protobuf 27, see https://github.com/protocolbuffers/protobuf/commit/d111589bc05f0c11d9d2b0e230bc3217f24feb40 (and probably some later commit that removed the method). According to the tags listed in the GitHub UI, it shouldn't be part of 26.

**Comment by h-vetinari** [comment]
> According to the tags listed in the GitHub UI, it shouldn't be part of 26.

The automatically generated tags don't work for backports, generally. Here's the commit for v26.x: https://github.com/protocolbuffers/protobuf/commit/043191b84d6061ed923d1c227ef38030f18fe619

**Comment by h-vetinari** [comment]
Seems that a related commit (https://github.com/bazelbuild/bazel/commit/26c05cb19a5935348d7f30a2caf6400d03c6bfd7) was backported to bazel 7, but not bazel 6

**Comment by xhochy** [comment]
That is still using `includingDefaultValueFields` without any arguments, i.e. it won't work with protibuf 26.

**Comment by h-vetinari** [comment]
So I may not understand bazel well-enough, but it's a bit problematic to have a build tool have such sensitive dependencies. Should we introduce a stand-alone bazel, kinda like we have [`cmake-no-system`](https://github.com/conda-forge/cmake-no-system-feedstock)?

**Comment by h-vetinari** [comment]
(I see no upstream movement for becoming compatible with protobuf v26, and getting stuck for weeks or months is hardly sustainable)

**Comment by xhochy** [comment]
We don't need a `no-system`, but we rather can use a bazel binary from upstream that is self-contained. I can do this or you can look into the PR history of my bazel 7 PR. There I used it for most of the PR.

**Comment by h-vetinari** [comment]
> We don't need a `no-system`, but we rather can use a bazel binary from upstream that is self-contained. I can do this or you can look into the PR history of my bazel 7 PR. There I used it for most of the PR.

I'm not sure we're talking about the same thing... I want a bazel variant where I don't have to worry about matching protobuf requirements. IIUYC, even if we revert https://github.com/conda-forge/bazel-feedstock/commit/61e77d29a09e6ae44a972e2cae1fea8d95b10b0d (+ clean-ups), we wouldn't be getting a protobuf-independent result here (which we could deal with in principle, but if upstream bazel takes month to achieve compatibility with a new protobuf major version, we're too seriously hampered IMO).

So I think what would make sense for packaging protobuf is exactly the kind of `bazel_nojdk` that is self-contained, but it would be nice to have this explicitly packaged, rather than pull that `sources:` block from 61e77d29a09e6ae44a972e2cae1fea8d95b10b0d  into other feedstocks that just want to use bazel.

**Pull request closed without merging**
